let configuration = {

    board_size : 15,
    maximum_number_of_letters: 7,

    alphabet : [
        {letter: "a", point: 1,  image: "a.png"},
        {letter: "b", point: 3,  image: "b.png"},
        {letter: "c", point: 3,  image: "c.png"},
        {letter: "d", point: 2,  image: "d.png"},
        {letter: "e", point: 1,  image: "e.png"},
        {letter: "f", point: 4,  image: "f.png"},
        {letter: "g", point: 2,  image: "g.png"},
        {letter: "h", point: 4,  image: "h.png"},
        {letter: "i", point: 1,  image: "i.png"},
        {letter: "j", point: 8,  image: "j.png"},
        {letter: "k", point: 5,  image: "k.png"},
        {letter: "l", point: 1,  image: "l.png"},
        {letter: "m", point: 3,  image: "m.png"},
        {letter: "n", point: 1,  image: "n.png"},
        {letter: "o", point: 1,  image: "o.png"},
        {letter: "p", point: 3,  image: "p.png"},
        {letter: "q", point: 10, image: "q.png"},
        {letter: "r", point: 1,  image: "r.png"},
        {letter: "s", point: 1,  image: "s.png"},
        {letter: "t", point: 1,  image: "t.png"},
        {letter: "u", point: 1,  image: "u.png"},
        {letter: "v", point: 4,  image: "v.png"},
        {letter: "w", point: 4,  image: "w.png"},
        {letter: "x", point: 8,  image: "x.png"},
        {letter: "y", point: 4,  image: "y.png"},
        {letter: "z", point: 10, image: "z.png"},
    ],

    cell_images: {
        NO_PROPERTY_CELL        : "empty.jpg",
        LETTER_DOUBLE_POINT_CELL: "h2.jpg",
        LETTER_TRIPLE_POINT_CELL: "h3.jpg",
        WORD_DOUBLE_POINT_CELL:   "k2.jpg",
        WORD_TRIPLE_POINT_CELL:   "k3.jpg"
    },

    special_cells: [
        {row: 0,  col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 0,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 12, property: WORD_TRIPLE_POINT_CELL},
        {row: 1,  col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 1,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 2,  col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 2,  col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 2,  col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 3,  col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 3,  col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 4,  col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 4,  col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 5,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 7,  col: 2,  property: WORD_DOUBLE_POINT_CELL},
        {row: 7,  col: 12, property: WORD_DOUBLE_POINT_CELL},
        {row: 8,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 10, col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 10, col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 11, col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 11, col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 12, col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 13, col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 13, col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 14, col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 14, col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 12, property: WORD_TRIPLE_POINT_CELL}
    ]
};