let configurationEn = {

    board_size : 15,
    maximum_number_of_letters: 7,

    alphabet : [
        {letter: "a", point: 1,  image: "en/a.png"},
        {letter: "b", point: 3,  image: "en/b.png"},
        {letter: "c", point: 3,  image: "en/c.png"},
        {letter: "d", point: 2,  image: "en/d.png"},
        {letter: "e", point: 1,  image: "en/e.png"},
        {letter: "f", point: 4,  image: "en/f.png"},
        {letter: "g", point: 2,  image: "en/g.png"},
        {letter: "h", point: 4,  image: "en/h.png"},
        {letter: "i", point: 1,  image: "en/i.png"},
        {letter: "j", point: 8,  image: "en/j.png"},
        {letter: "k", point: 5,  image: "en/k.png"},
        {letter: "l", point: 1,  image: "en/l.png"},
        {letter: "m", point: 3,  image: "en/m.png"},
        {letter: "n", point: 1,  image: "en/n.png"},
        {letter: "o", point: 1,  image: "en/o.png"},
        {letter: "p", point: 3,  image: "en/p.png"},
        {letter: "q", point: 10, image: "en/q.png"},
        {letter: "r", point: 1,  image: "en/r.png"},
        {letter: "s", point: 1,  image: "en/s.png"},
        {letter: "t", point: 1,  image: "en/t.png"},
        {letter: "u", point: 1,  image: "en/u.png"},
        {letter: "v", point: 4,  image: "en/v.png"},
        {letter: "w", point: 4,  image: "en/w.png"},
        {letter: "x", point: 8,  image: "en/x.png"},
        {letter: "y", point: 4,  image: "en/y.png"},
        {letter: "z", point: 10, image: "en/z.png"},
    ],

    cell_images: {
        NO_PROPERTY_CELL        : "empty.jpg",
        LETTER_DOUBLE_POINT_CELL: "h2.jpg",
        LETTER_TRIPLE_POINT_CELL: "h3.jpg",
        WORD_DOUBLE_POINT_CELL:   "k2.jpg",
        WORD_TRIPLE_POINT_CELL:   "k3.jpg"
    },

    special_cells: [
        {row: 0,  col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 0,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 12, property: WORD_TRIPLE_POINT_CELL},
        {row: 1,  col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 1,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 2,  col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 2,  col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 2,  col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 3,  col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 3,  col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 4,  col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 4,  col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 5,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 7,  col: 2,  property: WORD_DOUBLE_POINT_CELL},
        {row: 7,  col: 12, property: WORD_DOUBLE_POINT_CELL},
        {row: 8,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 10, col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 10, col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 11, col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 11, col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 12, col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 13, col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 13, col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 14, col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 14, col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 12, property: WORD_TRIPLE_POINT_CELL}
    ]
};

let configurationTr = {

    board_size : 15,
    maximum_number_of_letters: 7,

    alphabet : [
        {letter: "a", point: 1,  image: "tr/a.png"},
        {letter: "b", point: 3,  image: "tr/b.png"},
        {letter: "c", point: 4,  image: "tr/c.png"},
        {letter: "ç", point: 4,  image: "tr/c1.png"},
        {letter: "d", point: 3,  image: "tr/d.png"},
        {letter: "e", point: 1,  image: "tr/e.png"},
        {letter: "f", point: 7,  image: "tr/f.png"},
        {letter: "g", point: 5,  image: "tr/g.png"},
        {letter: "ğ", point: 8,  image: "tr/g1.png"},
        {letter: "h", point: 5,  image: "tr/h.png"},
        {letter: "ı", point: 2,  image: "tr/i1.png"},
        {letter: "i", point: 1,  image: "tr/i.png"},
        {letter: "j", point: 10, image: "tr/j.png"},
        {letter: "k", point: 1,  image: "tr/k.png"},
        {letter: "l", point: 1,  image: "tr/l.png"},
        {letter: "m", point: 2,  image: "tr/m.png"},
        {letter: "n", point: 1,  image: "tr/n.png"},
        {letter: "o", point: 2,  image: "tr/o.png"},
        {letter: "ö", point: 7,  image: "tr/o1.png"},
        {letter: "p", point: 5,  image: "tr/p.png"},
        {letter: "r", point: 1,  image: "tr/r.png"},
        {letter: "s", point: 2,  image: "tr/s.png"},
        {letter: "ş", point: 4,  image: "tr/s1.png"},
        {letter: "t", point: 1,  image: "tr/t.png"},
        {letter: "u", point: 2,  image: "tr/u.png"},
        {letter: "ü", point: 3,  image: "tr/u1.png"},
        {letter: "v", point: 7,  image: "tr/v.png"},
        {letter: "y", point: 3,  image: "tr/y.png"},
        {letter: "z", point: 4, image: "tr/z.png"},
    ],

    cell_images: {
        NO_PROPERTY_CELL        : "empty.jpg",
        LETTER_DOUBLE_POINT_CELL: "h2.jpg",
        LETTER_TRIPLE_POINT_CELL: "h3.jpg",
        WORD_DOUBLE_POINT_CELL:   "k2.jpg",
        WORD_TRIPLE_POINT_CELL:   "k3.jpg"
    },

    special_cells: [
        {row: 0,  col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 0,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 0,  col: 12, property: WORD_TRIPLE_POINT_CELL},
        {row: 1,  col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 1,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 1,  col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 2,  col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 2,  col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 2,  col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 3,  col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 3,  col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 4,  col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 4,  col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 5,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 5,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 6,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 7,  col: 2,  property: WORD_DOUBLE_POINT_CELL},
        {row: 7,  col: 12, property: WORD_DOUBLE_POINT_CELL},
        {row: 8,  col: 1,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 8,  col: 13, property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 0,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 9,  col: 14, property: LETTER_DOUBLE_POINT_CELL},
        {row: 10, col: 4,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 10, col: 10, property: LETTER_TRIPLE_POINT_CELL},
        {row: 11, col: 3,  property: WORD_DOUBLE_POINT_CELL},
        {row: 11, col: 11, property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 0,  property: WORD_TRIPLE_POINT_CELL},
        {row: 12, col: 7,  property: WORD_DOUBLE_POINT_CELL},
        {row: 12, col: 14, property: WORD_TRIPLE_POINT_CELL},
        {row: 13, col: 1,  property: LETTER_TRIPLE_POINT_CELL},
        {row: 13, col: 6,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 8,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 13, col: 13, property: LETTER_TRIPLE_POINT_CELL},
        {row: 14, col: 2,  property: WORD_TRIPLE_POINT_CELL},
        {row: 14, col: 5,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 9,  property: LETTER_DOUBLE_POINT_CELL},
        {row: 14, col: 12, property: WORD_TRIPLE_POINT_CELL}
    ]
};